# Documentation: https://kubectl.docs.kubernetes.io/guides/config_management/components/
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - csi.yaml

patches:
  - target:
      version: v1
      kind: StorageClass
      name: hcloud-volumes
    patch: |-
      - op: add
        path: /reclaimPolicy
        value: Retain
